nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['^http://localhost:[0-9]+']
        allow_headers: ['X-Custom-Auth']
        allow_methods: ['POST', 'PUT', 'GET', 'PATCH', 'DELETE']
        expose_headers: []
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~